package:
    name: nanopipe
    version: {{ GIT_DESCRIBE_TAG }}

build:
    number: {{ GIT_DESCRIBE_NUMBER }}

source:
    git_url: ..

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - make
        - psrchive
        - sqlite

test:
    imports:
        - nanopipe

about:
    home: https://github.com/demorest/nanopipe
