#! /usr/bin/env python
import string

# load psrchive, set it to not load full data from the files
import psrchive

# Standardize Arecibo receiver names
def rcvr_name(orig_name):
    if orig_name == 'lbw': return 'L-wide'
    elif orig_name == 'sbw': return 'S-wide'
    else: return orig_name

# Fix mislabelled files
def name_from_freq(freq):
    if (freq<400.0): return '327'
    if (freq<500.0): return '430'
    if (freq<1900.0): return 'L-wide'
    if (freq<3000.0): return 'S-wide'
    return 'unknown'

def get_rcvr_name(filename):
    no_amps_bak = psrchive.Profile.no_amps.fget()
    psrchive.Profile.no_amps.fset(True)
    arch = psrchive.Archive_load(filename)
    name_in_file = arch.get_receiver_name().strip()
    if arch.get_backend_name()=='PUPPI':
        nc = arch.get_nchan()
        freq = arch[0].get_centre_frequency(nc/2)
        freq_name = name_from_freq(freq)
        if freq_name != 'unknown': name_in_file = freq_name
    psrchive.Profile.no_amps.fset(no_amps_bak)
    return rcvr_name(name_in_file)

if __name__=="__main__":
    import sys
    try:
        fname = sys.argv[1]
        print get_rcvr_name(fname)
    except:
        sys.exit(1)
