#! /usr/bin/env python

# Command line interface to psrindex

import os, sys, string
from nanopipe import psrindex

from optparse import OptionParser
cmdline = OptionParser()
cmdline.add_option('-v', '--verbose',
        action='store_true', dest='verbose', default=False,
        help='More verbose output')

cmdline.add_option('-d', '--dbfile', 
        action='store', dest='dbfile', default='index.db',
        help='Database file')

# Operation mode parameters
cmdline.add_option('-s', '--select',
        action='store_true', dest='select', default=False,
        help='Print filenames matching selection')
cmdline.add_option('-l', '--link', 
        action='store_true', dest='link', default=False,
        help='Create symlinks to files matching selection in current directory')
cmdline.add_option('-a', '--add', dest='add_dir', default=[],
        action='append', type='string',
        help='Search the specified directory tree and add to DB')
cmdline.add_option('-f', '--diff', dest='diff_db', default=None,
        action='store', type='string',
        help='Print files in main DB not found in DIFF_DB')
cmdline.add_option('-b', '--bad', dest='badlist', default=[],
        action='append', type='string',
        help='Read the specified "bad.dat" file and flag DB entries')

# Selection parameters
cmdline.add_option('-B', '--backend', 
        action='store', dest='backend', default=None,
        help='Backend name')
cmdline.add_option('-S', '--source', 
        action='store', dest='source', default=None,
        help='Source name (partial string is allowed)')

(opt,args) = cmdline.parse_args()

if len(opt.add_dir)>0:

    db = psrindex.PSRIndex(opt.dbfile, create=True)
    db.verbose = opt.verbose

    for dir in opt.add_dir:
        db.add_files(dir)

if len(opt.badlist)>=0:

    db = psrindex.PSRIndex(opt.dbfile)
    db.verbose = opt.verbose

    for badlist in opt.badlist:
        if opt.verbose:
            print "Flagging bad files from '%s'" % (badlist,)
        last_reason = ''
        for l in open(badlist).readlines():
            if l.startswith('#'):
                continue
            stuff = l.rstrip().split(' ',1)
            fname = stuff[0]
            try:
                reason = stuff[1]
            except IndexError:
                reason = ''
            if reason.strip() == '"': reason=last_reason
            print "Bad: %s '%s'" % (fname, reason)
            db.flag_bad(fname,reason)
            last_reason = reason

if opt.diff_db is not None:

    db_main = psrindex.PSRIndex(opt.dbfile)
    db_diff = psrindex.PSRIndex(opt.diff_db)

    files_main = db_main.select(include_bad=True,as_dict=True)
    files_diff = db_diff.select(include_bad=True,as_dict=True)

    fnames_main = set(files_main.keys())
    fnames_diff = set(files_diff.keys())

    for fname in sorted(fnames_main.difference(fnames_diff)): 
        print files_main[fname].full_path

if opt.select or opt.link:

    db = psrindex.PSRIndex(opt.dbfile)
    db.verbose = opt.verbose

    if (opt.backend is None) or (opt.source is None):
        print "Specify backend and source"
        sys.exit(1)

    files = db.select('backend="%s" and source like "%%%s%%"' % (opt.backend, opt.source))

    for f in files:
        if opt.select:
            print f.full_path
        if opt.link:
            os.symlink(f.full_path, './'+f.fname)
